### ISSUE TITLE
Github error created with ACE on our server

### ISSUE THREAD

**Issue by smashbrand-kris** [danyaPostfactum/modx-ace#28]
We installed ACE in MODX via the package management in MODX.  When pushing updates on our server to Git for our website, we get an error (see below).  When we remove ACE off our server, we don't get the Git error anymore.  ACE was stored here on our server: core/packages/ace-1.4.2-pl/

Here's the Git error we kept getting when ACE was on our server:

no changes added to commit (use "git add" and/or "git commit -a")
my619des@my619design.com [~/public_html/cdalions]# git add .
fatal: Not a git repository: manager/assets/components/ace/ace/../../../../../.git/modules/manager/assets/components/ace/ace

We couldn't push to Git until we removed ACE off our server.

**Comment by danyaPostfactum** [comment]
I guess this is because of forgotten .git file in the Ace transport package. It was reported here: http://forums.modx.com/thread/81257/ace-code-editor-for-modx-revolution---support-thread?page=3#dis-post-481800

You could download the package and remove `\manager\assets\components\ace\ace\.git` file from zip.
I'll fix it in a next release.

Thank's for the report.

**Comment by danyaPostfactum** [comment]
Fixed in 1.4.3-pl
